version: '3.7'

services:
    backend:
        build:
            context: ./backend
        command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 backend.wsgi"
        expose:
            - 8080
        volumes:
            - ./backend:/usr/src/backend
    nginx:
        build:
            context: ./nginx
        ports:
            - 8000:8080
        volumes:
            # - build_folder:/var/www/frontend
            - ./backend:/usr/src/backend
        depends_on:
            - backend
              #- frontend

